name: scraper-boy

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out repo
      uses: actions/checkout@v3

    - name: Setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Installing packages
      run: pip install -r requirements.txt

    - name: Scrape and send email
      env:
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        TARGET_EMAIL: ${{ secrets.TARGET_EMAIL }}
      run: python send_email.py