name: scraper-boy

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Run email code
      env:
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        TARGET_EMAIL: ${{ secrets.TARGET_EMAIL }}
      run: python send_email.py